version: '3'
services:
  hmac-server:
    build: .
    container_name: hmac-server
    command: ./server
    networks:
      - hmac-net
    expose:
      - "8080"

  hmac-client:
    build: .
    container_name: hmac-client
    command: bash -c "sleep 3 && ./client"  # Delay to let server start
    networks:
      - hmac-net
    depends_on:
      - hmac-server

networks:
  hmac-net:
    driver: bridge
